version: '3'
 
services:
  mongo:
    container_name: "mongonew"
    image: mongo:latest  
    restart: unless-stopped
    ports:
      - "27017:27017"  
    volumes:
      - ./data/mongo:/data/db
    networks:
      - backend_app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
 
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"    
    networks:
      - backend_app-network
 
  backend:
    build:
      context: ./backend/chatbot
    ports:
      - "5020:5020"    
    depends_on:
      - mongo
    networks:
      - backend_app-network
 
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"   
    depends_on:
      - frontend
      - backend
    networks:
      - backend_app-network
 
networks:
  backend_app-network:
    driver: bridge
