version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network
    restart: always

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redisinsight_container
    ports:
      - "8001:8001"
    networks:
      - redis_network
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
